### ISSUE TITLE
mrd (most recent directories)

### ISSUE THREAD

**Issue by vimtoe** [lambdalisue/mr.vim#12]
hi, first - thank you! I have used this long time, the only thing missing is "mrd" (most recent directories), the functionality is already there in "mrr" (which only records git repos), I would like "mrd" as not every "project" is under version control (or atleast at first), I use vim tabs for projects (tcd) and then open windows within (lcd), to be able to record either all of these, and then list either all (both) or just local would be amazing!
Thank you for your time and effort, the plugin is great!

**Comment by lambdalisue** [comment]
It seems `DirChanged` autcmd can be used to implement that

**Comment by lambdalisue** [comment]
@vimtoe MRD is implemented.
